Issue 3.
greenpress/secrets-service pull request #6
Opened 2020-08-22 04:15 UTC by ShiraRotman

2020-08-23 23:55 UTC, ShiraRotman commented on server/models/secrets.js
> +		return new Promise((resolve,reject) =>
But I don't return the findByKey promise, I handle it in the function I call it from.

2020-08-25 08:16 UTC, davidmeirlevy requested changes

2020-08-25 08:16 UTC, davidmeirlevy commented on config/index.js
> +const MONGO_URI=process.env.MONGO_URI || 'mongodb://localhost/secrets-service';
you can revert all the changes in this file.

2020-08-25 08:16 UTC, davidmeirlevy commented on server/controllers/get.js
> +const Secret = require('../services/index');
services is a folder that should have `secrets-service.js` with a SecretsService object.
"index" is not a valid service file, because each service on the services folder should be independent.

2020-08-25 08:16 UTC, davidmeirlevy commented on server/controllers/set.js
> +const Secret = require('../services/index');
the same comment as for the get file.

2020-08-25 08:16 UTC, davidmeirlevy commented on server/dao/mongo/mongo-impl.js
> +const mongoose = require('mongoose')
should be 2 separated files:
- connect
- secret-model

if the model should have only 2 exported functions, you can't export them without store them as statics on mongoose.

2020-08-25 08:16 UTC, davidmeirlevy commented on server/dao/mongo/mongo-impl.js
> +	return MongoSecret.findOneAndUpdate({ tenant: tenant, key: key },
MongoSecret is also the "this" of this method function.

2020-08-25 08:16 UTC, davidmeirlevy commented on server/services/index.js
> +mongoose.connect(mongoUri,
the mongoose connect should be part of the mongoose implementation.

2020-08-25 08:16 UTC, davidmeirlevy commented on server/services/secrets.js
> +	return new Promise((resolve,reject) =>
the "findbykey" of mongoose is already a promise

2020-08-25 08:16 UTC, davidmeirlevy commented on server/services/secrets.js
> +module.exports = Secret;
it's better that this object will already use the mongo implementation for now, because the actual implementation should be injected to here, and not given by parameters.

2020-08-25 17:02 UTC, ShiraRotman commented on server/services/secrets.js
> +	return new Promise((resolve,reject) =>
Yes, but I use this promise, not return it as it is.

2020-08-25 18:48 UTC, ShiraRotman commented
I'm sorry, but instead of all this "ping-pong", maybe you could merge the PR to a branch, do the changes you want, and then merge it all to the master.

2020-08-26 13:01 UTC, davidmeirlevy commented
changed the PR, merging this one:
https://github.com/greenpress/secrets-service/pull/7

2020-08-26 13:01 UTC, closed without merging